name: CI/CD Deployment to GKE

on:
    push:
        branches:
            - master

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GKE_CLUSTER: "mlops-project-03-cluster"
    GKE_REGION: "us-central1"
    DEPLOYMENT_NAME: "mlops-app-project-03"
    REPOSITORY_NAME: "us-central1-docker.pkg.dev/ml-ops-amasha/mlops-project"
    IMAGE: "us-central1-docker.pkg.dev/ml-ops-amasha/mlops-project/mlops-app-project-03:latest"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v2

            - name: Authenticate with Google Cloud Platform
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Configure the Google Cloud
              run: |
                gcloud config set project $PROJECT_ID
                gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Build and Push the Docker Image
              run: |
                docker build -t $IMAGE:$GITHUB_SHA .
                docker push $IMAGE:$GITHUB_SHA

            - name: GKE Configurations
              run: |
                gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

            - name: Install gke-gcloud-auth-plugin
              run: |
                sudo apt-get update
                sudo apt-get install -y apt-transport-https ca-certificates gnupg
                echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
                curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
                sudo apt-get update
                sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
                echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

            - name: Final Deployment to GKE
              run: |
                kubectl apply -f kubernetes-deployment.yaml
                kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA

            

             